cache:
  key: apt-cache
  paths:
  - apt-cache/
    # for build_dependencies
  - libaccounts-glib

stages:
  - deps
  - build
  - test
  - deploy

build_dependencies:
  image: ubuntu:bionic
  stage: deps
  artifacts:
    paths:
      - staging
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - PACKAGES+=" wget" # for downloading dependencies
    - PACKAGES+=" libglib2.0-dev libsqlite3-dev libxml2-dev gtk-doc-tools libgirepository1.0-dev gobject-introspection libxml2-utils python3-gi python-gi-dev valac check python3-pip" # for libaccounts-glib
    - apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y $PACKAGES
    - pip3 install meson ninja

  script:
    - STAGING="$PWD/staging"

      # Build libaccounts-glib
    - LIBACCOUNTS_VERSION="master"
    - LIBACCOUNTS_ARCHIVE="libaccounts-glib-${LIBACCOUNTS_VERSION}.tar.bz2"
    - mkdir libaccounts-glib && cd libaccounts-glib
    - if [ ! -d "libaccounts-glib-${LIBACCOUNTS_VERSION}" ]; then
    -   if [ ! -f "$LIBACCOUNTS_ARCHIVE" ]; then
    -     wget -c -nv "https://gitlab.com/accounts-sso/libaccounts-glib/-/archive/master/$LIBACCOUNTS_ARCHIVE"
    -   fi
    -   tar xjf "$LIBACCOUNTS_ARCHIVE"
    - fi
    - cd "libaccounts-glib-${LIBACCOUNTS_VERSION}"
    - mkdir build 
    - meson build --prefix $STAGING --libdir lib
    - cd build
    - ninja
    - ninja install || true # This currently fails on gtkdoc, but the important bits get done


build_amd64:
  image: ubuntu:bionic
  stage: build
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - |
        apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y \
            qt5-qmake qttools5-dev-tools qtbase5-dev qtchooser pkg-config doxygen wget libglib2.0-dev libsqlite3-dev libxml2-dev gtk-doc-tools libgirepository1.0-dev gobject-introspection libxml2-utils python3-gi python-gi-dev valac check python3-pip
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y dbus-test-runner lcov gcovr

  script:
    - STAGING="$PWD/staging"
    - export PKG_CONFIG_PATH="$STAGING/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$STAGING/lib:$LD_LIBRARY_PATH"
    - export QT_SELECT=qt5
    - mkdir build
    - cd build
    - qmake CONFIG+=debug CONFIG+=coverage ..
    - make -j 4
  dependencies:
    - build_dependencies
  artifacts:
    paths:
      - build/

test_amd64:
  image: ubuntu:bionic
  stage: test
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - PACKAGES+=" wget" # for downloading dependencies
    - |
        apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y \
            qt5-qmake qttools5-dev-tools qtbase5-dev qtchooser pkg-config doxygen \
            $PACKAGES
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y dbus-test-runner lcov gcovr
  script:
    - STAGING="$PWD/staging"
    - export LD_LIBRARY_PATH="$STAGING/lib:$LD_LIBRARY_PATH"
    - find build | xargs touch # Avoid rebuilding
    - cd build
    - make coverage-html
  dependencies:
    - build_dependencies
    - build_amd64
  artifacts:
    paths:
      - build/

build_amd64_qt6:
  stage: build
  image: ubuntu:jammy
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y qmake6 qt6-base-dev pkg-config libqt6sql6-sqlite doxygen libdbus-1-dev g++ make libglib2.0-dev gtk-doc-tools libgirepository1.0-dev gobject-introspection libxml2-utils python3-gi python-gi-dev valac check python3-pip libsqlite3-dev libxml2-dev
  script:
    - STAGING="$PWD/staging"
    - find $STAGING
    - export PKG_CONFIG_PATH="$STAGING/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$STAGING/lib:$LD_LIBRARY_PATH"
    - mkdir build
    - cd build
    - qmake6 CONFIG+=debug CONFIG+=coverage ..
    - make -j 4
  dependencies:
    - build_dependencies
  artifacts:
    paths:
      - build/

test_amd64_qt6:
  stage: test
  image: ubuntu:jammy
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y dbus-test-runner libqtdbusmock1-dev libqtdbustest1-dev lcov gcovr make qmake6 qt6-base-dev pkg-config libqt6sql6-sqlite doxygen libdbus-1-dev g++ make libsqlite3-dev libxml2-dev libglib2.0-dev
  script:
    - STAGING="$PWD/staging"
    - export LD_LIBRARY_PATH="$STAGING/lib:$LD_LIBRARY_PATH"
    - find build | xargs touch # Avoid rebuilding
    - cd build
    - make coverage-html
  dependencies:
    - build_dependencies
    - build_amd64_qt6
  artifacts:
    paths:
      - ./

pages:
  stage: deploy
  image: ubuntu:bionic
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - |
        apt-get update -yq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y \
            qt5-qmake qttools5-dev-tools qtbase5-dev qtchooser pkg-config doxygen wget libglib2.0-dev libsqlite3-dev libxml2-dev gtk-doc-tools libgirepository1.0-dev gobject-introspection libxml2-utils python3-gi python-gi-dev valac check python3-pip
    - apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y dbus-test-runner lcov gcovr
  script:
    - find build | xargs touch # Avoid rebuilding
    - cd build
    - make docs
    - cd ..
    - mkdir public
    - cp -a build/coverage-html public/coverage
    - cp -a build/doc/html/* public/
  dependencies:
    - test_amd64
  artifacts:
    paths:
      - public
  only:
    - master

